server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false   # Eureka server never registers itself
    fetch-registry: false         # Eureka server never fetches other registries

  instance:
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.cloud.netflix.eureka: INFO
    com.netflix.discovery: INFO
    root: INFO
