server:
  port: 8081

spring:
  application:
    name: quiz-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  circuitbreaker:
    instances:
      questionServiceBreaker:
        slidingWindowSize: 10
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 3
        registerHealthIndicator: true

logging:
  level:
    root: INFO
